require: rubocop-rspec

# increase the default metric limits to more realistic levels
Metrics/BlockLength:
  Max: 200

Metrics/LineLength:
  Max: 200

Metrics/MethodLength:
  Max: 200

Metrics/AbcSize:
  Max: 100

Metrics/ClassLength:
  Max: 500

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 20


# Don't be picky about string quoting
Style/PercentLiteralDelimiters:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Layout/MultilineMethodCallBraceLayout:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

# Disabling unrealistic rubocop RSpec cops
RSpec/HookArgument:
   Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

# We want to call gem files multiple times if they have a ruby version dependency
Bundler/DuplicatedGem:
  Enabled: false

# When there are dependencies we have duplicate gems so they cant be ordered
Bundler/OrderedGems:
  Enabled: false

# Useless detection on Windows
Layout/EndOfLine:
  Enabled: false
